services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: learn-api
    ports:
      - 3001:3000
    depends_on:
      - postgres
    volumes:
      - ./:/app/
    networks:
      - integration

  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=learn
    ports:
      - "15432:5432"
    networks:
      - integration

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "email@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - "54321:80"
    depends_on:
      - postgres
    networks:
      - integration

networks:
  integration:
    name: integration
