// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Subject struct {
	ID        int32
	Name      string
	TotalTime int32
	Avarage   int32
	UserID    int32
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID        int32
	Name      string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamptz
}
