// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/LuanTenorio/learn-api/internal/auth/dto"
	mock "github.com/stretchr/testify/mock"
)

// AuthUseCase is an autogenerated mock type for the AuthUseCase type
type AuthUseCase struct {
	mock.Mock
}

// Login provides a mock function with given fields: ctx, loginDto
func (_m *AuthUseCase) Login(ctx context.Context, loginDto *dto.LoginDTO) (string, error) {
	ret := _m.Called(ctx, loginDto)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.LoginDTO) (string, error)); ok {
		return rf(ctx, loginDto)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.LoginDTO) string); ok {
		r0 = rf(ctx, loginDto)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.LoginDTO) error); ok {
		r1 = rf(ctx, loginDto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthUseCase creates a new instance of AuthUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthUseCase {
	mock := &AuthUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
