// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/LuanTenorio/learn-api/internal/user/dto"
	entity "github.com/LuanTenorio/learn-api/internal/user/entity"

	mock "github.com/stretchr/testify/mock"
)

// UserUseCase is an autogenerated mock type for the UserUseCase type
type UserUseCase struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: ctx, userDto
func (_m *UserUseCase) CreateUser(ctx context.Context, userDto *dto.CreateUserDTO) (*entity.User, error) {
	ret := _m.Called(ctx, userDto)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateUserDTO) (*entity.User, error)); ok {
		return rf(ctx, userDto)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateUserDTO) *entity.User); ok {
		r0 = rf(ctx, userDto)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.CreateUserDTO) error); ok {
		r1 = rf(ctx, userDto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserUseCase creates a new instance of UserUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserUseCase {
	mock := &UserUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
